AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyKeyName:
    Description: Selection the key from the list
    Type: AWS::EC2::KeyPair::KeyName

  MyEnvironment: 
    Description: Select the environment from the list 
    Type: String
    Default: dev
    AllowedValues:
      - dev 
      - prod 
      - staging
Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-05fa00d4c63e32376
    us-east-2:
      HVM64: ami-0568773882d492fc8

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    staging:
      instanceType: t2.small
    prod:
      instanceType: t2.medium
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [MyRegionMap, !Ref 'AWS::Region', HVM64]
      InstanceType: !FindInMap [MyEnvironmentMap, !Ref MyEnvironment , instanceType]
      KeyName: !Ref MyKeyName