AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b0dcb5067f052a63
      InstanceType: t2.micro 
      KeyName: cfn-key-1