AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MyKeyName:
    Description: Select the Keypair from the list
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-0b0dcb5067f052a63
    us-east-2:
      HVM64: ami-0beaa649c482330f7

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [MyRegionMap, !Ref AWS::Region, HVM64]
      InstanceType: t2.micro 
      KeyName: !Ref MyKeyName