AWSTemplateFormatVersion: "2010-09-09"
Description: Az Parameter Type

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName

  MyAvailabilityZone:
    Description: Select the Az from the list 
    Type: String
    Default: us-east-1a
    AllowedValues:
      - "us-east-1a"
      - "us-east-1b"
      - "us-east-1c"

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      AvailabilityZone: !Ref MyAvailabilityZone
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG 
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0