AWSTemplateFormatVersion: "2010-09-09"
Description: AZ Parameter Demo 
Parameters:
  MyKeyName:
    Description: Select the Key Name from the list
    Type: AWS::EC2::KeyPair::KeyName

  MyAvailabilityZone:
    Description: Select the Availability Zone from the list 
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  MyInstanceType:
    Description: Select the EC2 instance type from SSM 
    Type: AWS::SSM::Parameter::Value<String>

    


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09d3b3274b6c5d4aa
      InstanceType: !Ref MyInstanceType
      AvailabilityZone: !Ref MyAvailabilityZone
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0