AWSTemplateFormatVersion: "2010-09-09"
Description: Creating an EC2 Instance 
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro