AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 Instance 
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      ImageId: ami-05fa00d4c63e32376
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

# Elastic IP For The EC2 Instance

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance


# Our EC2 Security Group

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp 
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22

# Our Second Security Group

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections from specified CIDR ranges
      SecurityGroupIngress:
        - IpProtocol: tcp 
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80